# Generated by Django 5.0.4 on 2025-03-17 12:51

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_department', models.CharField(max_length=150, unique=True)),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('middle_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=25, unique=True)),
                ('address_line_1', models.CharField(max_length=300)),
                ('address_line_2', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=150)),
                ('nationality', django_countries.fields.CountryField(max_length=200)),
                ('zip_or_post_code', models.CharField(max_length=20)),
                ('employment_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('job_title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('FT', 'Fulltime'), ('PT', 'Parttime'), ('FX', 'Flexible'), ('CT', 'Contract')], max_length=120)),
                ('supervisor', models.CharField(blank=True, max_length=120, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, to='API.department')),
            ],
            options={
                'verbose_name': 'Employee Detail',
                'verbose_name_plural': 'Employee Details',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.OneToOneField(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.employeedetails'),
        ),
    ]
