# Generated by Django 5.0.4 on 2025-03-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_employeedetails_next_of_kin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('dept', models.ManyToManyField(blank=True, max_length=200, null=True, to='API.department')),
            ],
        ),
        migrations.CreateModel(
            name='employeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('Advanced', 'Advanced'), ('Midlevel', 'Midlevel'), ('Beginer', 'Beginer')], max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employeedetails')),
                ('skills_obtained', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('training_provider', models.CharField(max_length=200)),
                ('training_location', models.CharField(choices=[('ONSITE', 'onsite'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=200)),
                ('duration', models.DurationField()),
                ('start_date', models.DateField()),
                ('training_date', models.ManyToManyField(blank=True, max_length=200, null=True, to='API.department')),
            ],
        ),
    ]
